---
version: '3.8'

services:
  app:
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${APP_DB_DATABASE}
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata      
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always

volumes:
  pg-data:
