---
- name: Updates apt cache
  apt:
    update_cache: yes

- name: Installs necessary packages
  apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3-pip

- name: Install Docker Module for Python
  pip:
    name:
      - docker
